models:
  - type: main
    engine: openai
    model: gpt-4

rails:
  config:
    jailbreak_detection:
      lp_threshold: 89.79
      ps_ppl_threshold: 1845.65

  input:
    flows:
      - self check input
